[package]
name = "runit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.15", features = ["derive"] }
serde = { version = "1.0.206", features = ["derive"] }
toml = "0.8.19"
dirs = "5.0.1"
