use anyhow::Result;
use std::{fs, io::Write};

use crate::utils::exec::exec;

// Container pkgs references folders is
// ~/.run-it/

pub fn create_ref(package: String, container: String) -> Result<()> {
    let content = format!(
        "
#
# Wrapper generated by run-it tool
#
    
runit run {} -c {}

        ",
        package, container
    );

    let directory = dirs::home_dir().unwrap().join(".run-it");
    let file_dir = directory.join(&package);
    if let Ok(mut file) = fs::File::create(&file_dir) {
        file.write_all(content.as_bytes())?;
        exec(&format!("chmod +x {}", file_dir.to_str().unwrap()))?;
        println!("Ref created");
    } else {
        println!(
            "Creating binaries folder in: {}",
            directory.to_str().unwrap()
        );
        fs::create_dir(directory)?;
        create_ref(package, container)?;
    }

    Ok(())
}
